import type { NextPage } from 'next'
import React, {useEffect} from 'react'
import { useSelector, useDispatch } from 'react-redux'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import {toast} from "react-toastify"
import styles from '../styles/Home.module.css'
import { useContactsQuery, useDeleteContactMutation } from '../services/contactsApi'
import { setIden } from '../services/idSlice'

const Home: NextPage = () => {
  const {data, isLoading, error } = useContactsQuery()

  const [deleteContact] = useDeleteContactMutation()

  const dispatch = useDispatch()

  // const identi = useSelector((state) => state.identifier)

  // const { id } = identi

  // const handleEdit = (id: any) => {
  //   dispatch(setIden({id}))
  // }

  
  useEffect(() => {
    if(error) {
      toast.error("Something went wrong!")
    }
  }, [error])

  if(isLoading) {
    return <h3>Loading...</h3>
  }

  const handleDelete = async(id: any) => {
    if(window.confirm("Are you sure you want to delete Contact ?")) {
        await deleteContact(id)
        toast.success("Contact deleted successfully")
    }
  }
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>




      <div>

      <div>
        <Link href="/add-contact">
          <button>
            Add Contact
          </button>
        </Link>
      </div>

      <div>

    <table>
      <thead>
        <tr>
          <th style={{textAlign: "center" }}>No</th>
          <th style={{textAlign: "center" }}>Name</th>
          <th style={{textAlign: "center" }}>Email</th>
          <th style={{textAlign: "center" }}>Contact</th>
          <th style={{textAlign: "center" }}>Actions</th>
        </tr>
      </thead>
      <tbody>
        {
          data?.map((item: any, index: number) => {
           return (
            <tr key={item.id}>
              <th scope='row'> {index + 1} </th>
              <td> {item.name} </td>
              <td> {item.email} </td>
              <td> {item.contact} </td>
              <td>
                <Link href={`/edit-contact/${item.id}`} >
                  <button onClick={() =>  dispatch(setIden(item.id))}>Edit</button>
                </Link>
                <button onClick={() => handleDelete(item.id)} >Delete</button>
                <Link href={`/info-page/${item.id}`} >
                  <button>View</button>
                </Link>
              </td>
            </tr>
           )
          })
        }
      </tbody>
    </table>

      </div>

      </div>
    </div>
  )
}

export default Home
